11.Encuentra el maximo producto de números adyacentes en la siguiente tabla

In [6]:
import numpy as np

lista = np.loadtxt("problema11.txt",dtype='i',delimiter=' ')

print(lista)


[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 33 67 46 55 12 32 63 93

In [16]:
maxx= 0
#ndenumarate permite iterar sobre indices y valores de un array
for index, x in np.ndenumerate(lista):
    try:
        hor = x * lista[index[0],index[1]+1]*lista[index[0],index[1]+2] \
        *lista[index[0],index[1]+3]
    except:
        pass
    try:
        vert = x * lista[index[0]+1,index[1]]*lista[index[0]+2,index[1]] \
        *lista[index[0]+3,index[1]]
    except:
        pass
    try:
        diag1 = x * lista[index[0]+1,index[1]+1]*lista[index[0]+2,index[1]+2] \
        *lista[index[0]+3,index[1]+3]
    except:
        pass
    try:
        diag2 = x * lista[index[0]+1,index[1]-1]*lista[index[0]+2,index[1]-2] \
        *lista[index[0]+3,index[1]-3]
    except:
        pass
    
   
    if max(maxx,hor,vert,diag1,diag2) > maxx:
        maxx = max(maxx,hor,vert,diag1,diag2)
        indice = (index[0],index[1])
        
    
print(maxx)
print(indice)

70600674
(12, 6)


12. Encuentra el primer numero triangular que tiene mas de 500 divisores

In [18]:
# Highly divisible triangular number
import time

start = time.time()


def e12():
    tri = 1
    nat = 1
    div = 4  # Every even number that is greater than 2 is divisible by 1, 2, half and itself without a reminder.
    while div < 501:
        nat += 1
        tri += nat
        if tri % 2 == 0 and tri > 250000:  # I don't know exactly, I took only even numbers > 500 ** 2
            div = 4
            for j in range(3, int(tri ** 0.5) + 1):
                if tri % j == 0:
                    div += 2     # Each time we have 2 divisors
    print("Triangular number:", tri)
    print("Divisors:", div)
    end = time.time() - start
    print("Runtime =", end)


e12()

Triangular number: 76576500
Divisors: 576
Runtime = 1.3942983150482178


13. Encuentra los primeros 10 digitos de la suma de los siguientes 100 numeros de 50 digitos.

In [30]:
import numpy as np
lista = open("problema13.txt")

summ=0
for line in lista:
    summ += int(line[:12]) #suma solo los primeros 12 digitos
print(str(summ)[0:10])

lista.close()




5537376230


14. Secuencia de Collatz mas larga para un numero menor a 1 000 000

In [9]:
# No necesitamos calcular Collatz(n) para n < 500000 porque Collatz(2n) > Collatz(n)
#Si n es impar, collatz(n) = collatz((3n+1)/2)+2

import numpy as np

values = np.zeros(1000000)

def contar(n):
    if values[n] != 0:
        return values[n]

    if n % 2 ==0:
        values[n] = 1+contar(n/2)
    else:
        values[n] = 2+contar((3*n+1)/2)
        
    return values[n]

contar(2)
longestchain=0
answer=-1

for n in range(500000,1000000):
    if contar(n) > longestchain:
        longestchain = contar(n)
        answer = n
        
print(answer)  
    
    
    




    

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [16]:


from math import *

factorial(40) / (factorial(20)**2)


137846528820.0

Calcula la cantidad de caminos para ir de una esquina de un cuadrilatero a otra de 20*20

In [26]:
# Sea countR(m,n) la cantidad de caminos de una cuadricula de m*n
#evidentemente R(m,n) = R(m,n-1) + R(m-1,n)

def countR(m,n):
    if n==0 or m ==0:
        return 1
    return(countR(m,n-1) + countR(m-1,n)) 
print(countR(4,4)) 
    

70


In [38]:
# un poco mas rapido
m=21
n=21
cache = np.full((m,n),-1,dtype='f')



def countR(m,n):
    if n==0 or m==0:
        return 1
    
    if cache[m,n] != -1:
        return cache[m,n]
    
    cache[m,n] = countR(m,n-1) + countR(m-1,n)
    return cache[m,n]

print(countR(m-1,n-1))



137846550000.0


In [40]:
#Solucion iterativa

#Sea grid[m,n] la cantidad de caminos de cuadricula de m*n

m=20
n=20


grid = np.full((m+1,n+1),-1,dtype='f')

for i in range(0,m+1):
    grid[i][0] = 1
    
for j in range(0,n+1):
    grid[0][j] = 1

for i in range(1,m+1):
    for j in range(1,n+1):
        grid[i][j] = grid[i-1][j] + grid[i][j-1]
        
print(grid)

[[1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
  1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
  1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
  1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
  1.0000000e+00]
 [1.0000000e+00 2.0000000e+00 3.0000000e+00 4.0000000e+00 5.0000000e+00
  6.0000000e+00 7.0000000e+00 8.0000000e+00 9.0000000e+00 1.0000000e+01
  1.1000000e+01 1.2000000e+01 1.3000000e+01 1.4000000e+01 1.5000000e+01
  1.6000000e+01 1.7000000e+01 1.8000000e+01 1.9000000e+01 2.0000000e+01
  2.1000000e+01]
 [1.0000000e+00 3.0000000e+00 6.0000000e+00 1.0000000e+01 1.5000000e+01
  2.1000000e+01 2.8000000e+01 3.6000000e+01 4.5000000e+01 5.5000000e+01
  6.6000000e+01 7.8000000e+01 9.1000000e+01 1.0500000e+02 1.2000000e+02
  1.3600000e+02 1.5300000e+02 1.7100000e+02 1.9000000e+02 2.1000000e+02
  2.3100000e+02]
 [1.0000000e+00 4.0000000e+00 1.0000000e+01 2.0000000e+01 3.5000000e+01
  5.6000000e+

In [49]:
a=str(2**1000)
summ=0
for i in a:
    summ = summ +int(i)    
print(summ)

1366
